export {
  SCAFFOLD_DOCUMENT_FORMAT_VERSION,
  CourseDocumentAttrsSchema,
  COURSE_THEME_NUMERIC_BOUNDS,
  CourseThemeColorPaletteSchema,
  CourseThemeCssColorSchema,
  CourseThemeDesignSchema,
  CourseThemeStateColorsSchema,
  CourseThemeTypographySchema,
  CourseThemeValuesSchema,
  PersistedCourseThemeSchema,
  ScaffoldArtifactSchema,
  ScaffoldDocumentContentSchema,
  CourseModeSchema,
  DEFAULT_IMAGE_POSITION,
  HorizontalAlignmentSchema,
  ImagePositionSchema,
  OverflowModeSchema,
  SurfaceAttrsSchema,
  SurfaceBackgroundSchema,
  SurfaceRegionToggleSchema,
  SurfaceSettingsSchema,
  SurfaceSizeSchema,
  VerticalContentPositionSchema,
  type CourseDocumentAttrs,
  type CourseThemeColorPalette,
  type CourseThemeCssColor,
  type CourseThemeDesign,
  type CourseThemeStateColors,
  type CourseThemeTypography,
  type CourseThemeValues,
  type PersistedCourseTheme,
  type ScaffoldArtifact,
  type ScaffoldDocumentContent,
  type CourseMode,
  type HorizontalAlignment,
  type ImagePosition,
  type OverflowMode,
  type SurfaceAttrs,
  type SurfaceBackground,
  type SurfaceRegionToggle,
  type SurfaceSettings,
  type SurfaceSize,
  type VerticalContentPosition,
} from "@scaffold/contracts";
