import { z } from "zod";

export const CodeBlockLanguageSchema = z.enum([
  "plaintext",
  "arduino",
  "bash",
  "c",
  "cpp",
  "csharp",
  "css",
  "diff",
  "go",
  "graphql",
  "ini",
  "java",
  "javascript",
  "json",
  "kotlin",
  "less",
  "lua",
  "makefile",
  "markdown",
  "objectivec",
  "perl",
  "php",
  "php-template",
  "python",
  "python-repl",
  "r",
  "ruby",
  "rust",
  "scss",
  "shell",
  "sql",
  "swift",
  "typescript",
  "vbnet",
  "wasm",
  "xml",
  "yaml",
]);
export type CodeBlockLanguage = z.infer<typeof CodeBlockLanguageSchema>;

export const CODE_BLOCK_LANGUAGE_LABELS: Record<CodeBlockLanguage, string> = {
  plaintext: "Plain text",
  arduino: "Arduino",
  bash: "Bash",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  css: "CSS",
  diff: "Diff",
  go: "Go",
  graphql: "GraphQL",
  ini: "INI",
  java: "Java",
  javascript: "JavaScript",
  json: "JSON",
  kotlin: "Kotlin",
  less: "Less",
  lua: "Lua",
  makefile: "Makefile",
  markdown: "Markdown",
  objectivec: "Objective-C",
  perl: "Perl",
  php: "PHP",
  "php-template": "PHP template",
  python: "Python",
  "python-repl": "Python REPL",
  r: "R",
  ruby: "Ruby",
  rust: "Rust",
  scss: "SCSS",
  shell: "Shell",
  sql: "SQL",
  swift: "Swift",
  typescript: "TypeScript",
  vbnet: "VB.NET",
  wasm: "WebAssembly",
  xml: "XML / HTML",
  yaml: "YAML",
};

export const CodeBlockDataSchema = z.object({
  type: z.literal("code_block").default("code_block"),
  language: CodeBlockLanguageSchema.default("plaintext"),
  showCopyButton: z.boolean().default(true),
});
export type CodeBlockData = z.infer<typeof CodeBlockDataSchema>;
