export {
  canInsertNodeAt,
  deleteNodeChecked,
  duplicateNodeChecked,
  insertNodeChecked,
  replaceRangeWithNodeChecked,
  type CheckedDuplicateNodeResult,
  type CheckedMutationIssue,
  type CheckedMutationResult,
} from "./commands/checked-transactions";
export * from "./content-model";
export { createCourseStructureModule } from "./course-structure";
export type {
  CourseSection,
  CourseSectionId,
  CourseStructure,
  CourseStructureCommand,
  CourseStructureCommandIssue,
  CourseStructureCommandIssueCode,
  CourseStructureCommandResult,
  CourseStructureCommandResultHandler,
  CourseStructureIssue,
  CourseStructureIssueCode,
  CourseStructureModule,
  CourseStructureValidationResult,
  CourseStructureValidator,
  CourseSurface,
  NonEmptyReadonlyArray,
  PageCourseStructure,
  SectionedSlideshowCourseStructure,
  SurfaceDestination,
  SurfaceId,
  UnsectionedSlideshowCourseStructure,
} from "./course-structure";
export { CourseDocumentNode, DocumentNode } from "./nodes";
export {
  defineCourseDocumentMigration,
  migrateCourseDocumentJSON,
  readCourseDocumentFormatVersion,
  runCourseDocumentMigrationSteps,
  validateCourseDocumentJSON,
  validateCourseDocumentMigrationPlan,
  validateEmbeddedNodeIdentities,
  type AppliedCourseDocumentMigration,
  type CourseDocumentIssue,
  type CourseDocumentIssueCode,
  type CourseDocumentMigrationErrorCode,
  type CourseDocumentMigrationResult,
  type CourseDocumentMigrationStep,
  type CourseDocumentMigrationStepResult,
  type CourseDocumentValidationResult,
  type EmbeddedNodeIdentityIssue,
  type EmbeddedNodeIdentityIssueCode,
  type EmbeddedNodeIdentityValidationResult,
} from "./validation";
export {
  getSurfaceViewSettings,
  readSurfaceViewSettings,
  readSurfaceViewSettingsFromProseMirrorDoc,
  type SurfaceViewSettings,
} from "./surface-view-settings";
